name: heydoc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^3.1.5
  provider: ^4.1.3+1
  firebase_analytics: ^6.0.1
  cupertino_icons: ^1.0.0
  flutter_spinkit: ^4.1.2+1
  cloud_firestore: ^0.14.1+2
  firebase_auth: ^0.18.1+1
  focused_menu: ^1.0.1
  firebase_storage: ^4.0.1
  barcode_scan: ^2.0.1
  file_picker: ^1.12.0
  introduction_screen: ^1.0.9
  flutter_local_notifications: ^1.4.4+4
  firebase_dynamic_links: ^0.6.0
  share: ^0.6.5+2
  agora_rtc_engine: ^1.0.15
  permission_handler: ^5.0.1+1
  google_sign_in: ^4.0.4
  open_file: ^3.0.3
  dio: ^3.0.10
  image_picker: ^0.6.0+17
  flutter_launcher_icons: "^0.8.0"
  chewie: ^0.12.1+1
  showcaseview: ^0.1.6
  shared_preferences: '>=0.5.12+4 <2.0.0'
  tezster_dart: ^2.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/inside/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/
    - assets/onboard/
    - assets/auth/
    - assets/inside/
  uses-material-design: true
